#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONDA_ENV_NAME="${1:-${CONDA_ENV_NAME:-langchain}}"

have_cmd() {
  command -v "$1" >/dev/null 2>&1
}

resolve_conda_prefix() {
  if [[ -n "${CONDA_PREFIX:-}" && "${CONDA_DEFAULT_ENV:-}" == "$CONDA_ENV_NAME" ]]; then
    echo "$CONDA_PREFIX"
    return 0
  fi
  if ! have_cmd conda; then
    return 1
  fi
  local prefix=""
  prefix="$(conda env list | awk -v env="$CONDA_ENV_NAME" '$1==env {print $NF; exit}')"
  [[ -n "$prefix" ]] || return 1
  echo "$prefix"
}

CONDA_PREFIX_RESOLVED="$(resolve_conda_prefix || true)"
if [[ -z "$CONDA_PREFIX_RESOLVED" ]]; then
  echo "Error: could not resolve conda env '$CONDA_ENV_NAME'. Create/activate it first."
  exit 1
fi

ACTIVATE_DIR="$CONDA_PREFIX_RESOLVED/etc/conda/activate.d"
DEACTIVATE_DIR="$CONDA_PREFIX_RESOLVED/etc/conda/deactivate.d"
ACTIVATE_HOOK="$ACTIVATE_DIR/langchain-autostart-services.sh"
DEACTIVATE_HOOK="$DEACTIVATE_DIR/langchain-autostart-services.sh"

mkdir -p "$ACTIVATE_DIR" "$DEACTIVATE_DIR"

cat > "$ACTIVATE_HOOK" <<EOF
#!/usr/bin/env bash
# Auto-generated by scripts/install_conda_hooks.sh
if [[ "\${CONDA_DEFAULT_ENV:-}" != "$CONDA_ENV_NAME" ]]; then
  return 0 2>/dev/null || exit 0
fi
if [[ "\${LANGCHAIN_DISABLE_AUTOSTART:-0}" == "1" ]]; then
  return 0 2>/dev/null || exit 0
fi
"$ROOT_DIR/scripts/conda_autostart_services.sh" start || true
EOF

cat > "$DEACTIVATE_HOOK" <<EOF
#!/usr/bin/env bash
# Auto-generated by scripts/install_conda_hooks.sh
if [[ "\${LANGCHAIN_AUTOSTOP_ON_DEACTIVATE:-0}" != "1" ]]; then
  return 0 2>/dev/null || exit 0
fi
"$ROOT_DIR/scripts/conda_autostart_services.sh" stop || true
EOF

chmod +x "$ACTIVATE_HOOK" "$DEACTIVATE_HOOK"

echo "Installed conda hooks into:"
echo "  $ACTIVATE_HOOK"
echo "  $DEACTIVATE_HOOK"
